# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo1111' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo1111
   
  
  pod 'YYCache'
  target 'demo1111Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo1111UITests' do
    # Pods for testing
  end

end
